[project]
name = "ft_package"
version = "0.0.1"
description = "A sample test package"
authors = [
  { name="Nour", email="nsmail@42.fr" }]
readme = "README.md"
license = {text = "MIT"}
maintainers = [{name = "Nour", email = "nsmail@42.fr"}]
[project.urls]
Homepage = "https://github.com/zaboulaza/ft_package"
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"